### ISSUE TITLE
All test cases doesn't pass for https://www.hackerrank.com/challenges/candies

### ISSUE THREAD

**Issue by sarathnair** [ehotinger/HackerRank#7]
The solution you posted for /master/Candies/Solution.cpp doesn't pass test cases 11 and 12

**Comment by ehotinger** [comment]
Thanks, I'll look into it when I get a chance. Seems like they added additional test cases since I've posted the original solution. If you've already fixed the issue with the original algorithm, feel free to make a PR and I'll merge it. Also, if you know the input which makes it fail and you can post that, it would be helpful as well

**Comment by kosalape** [comment]
initialize TotalCandies as a long long int. That would do it.

**Comment by jakchod** [comment]
You need long long int for solution.

**Comment by ehotinger** [comment]
@jakchod finally looked at this almost a year later ;) - yeah, they changed the problem description. Feel free to make PRs to this repo!
